// export const SET_ADMIN = "APP/SET_ADMIN"
// export const LOGIN = "APP/LOGIN"
// export const AUTHME = "APP/AUTHME"
// export const LOGIN_STATE = "APP/LOGIN_STATE"
// export const SHOW_ALERT = "APP/SHOW_ALERT"
// export const HIDE_ALERT = "APP/HIDE_ALERT"



export const REQUEST_FILTERS = "FILTER/REQUEST"
export const SET_FILTERS = "FILTER/SET"
export const SET_FILTERS_LIST = "FILTER/SET_LIST"

export const SET_FILTER = "FILTER/SET_CURRENT"
export const POST_FILTER = "FILTER/POST"
export const CREATE_FILTER = "FILTER/CREATE"
export const EDIT_FILTER = "FILTER/EDIT"
export const DELETE_FILTER = "FILTER/DELETE"

export const RECPOINTS = {
    REQUEST: "RECPOINT/REQUEST",
    SET: "RECPOINT/SET",
    SET_CURRENT: "RECPOINT/SET_CURRENT",
    POST: "RECPOINT/POST",
    CREATE: "RECPOINT/CREATE",
    EDIT: "RECPOINT/EDIT",
    DELETE: "RECPOINT/DELETE",
}

export const MARKERS = {
    REQUEST: "MARKERS/REQUEST",
    SET: "MARKERS/SET",
    SET_CURRENT: "MARKERS/SET_CURRENT",
    POST: "MARKERS/POST",
    CREATE: "MARKERS/CREATE",
    EDIT: "MARKERS/EDIT",
    DELETE: "MARKERS/DELETE",
}


export const PARTNERS = {
    REQUEST: "PARTNERS/REQUEST",
    SET: "PARTNERS/SET",
    SET_CURRENT: "PARTNERS/SET_CURRENT",
    POST: "PARTNERS/POST",
    CREATE: "MARKERSPARTNERSCREATE",
    EDIT: "PARTNERS/EDIT",
    DELETE: "PARTNERS/DELETE",
}

export const USERS = {
    REQUEST: "USERS/REQUEST",
    SET: "USERS/SET",
    SET_CURRENT: "USERS/SET_CURRENT",
    POST: "USERS/POST",
    CREATE: "USERS/CREATE",
    EDIT: "USERS/EDIT",
    DELETE: "USERS/DELETE",
}


export const STATS = {
    REQUEST: "STATS/REQUEST",
    SET: "STATS/SET",
    SET_MODELS: "STATS/SET_MODELS",
    POST: "STATS/POST",
    CREATE: "STATS/CREATE",
    EDIT: "USERSTATS/EDIT",
    DELETE: "STATS/DELETE",
}

// export const REQUEST_ADMINS = "ADMINS/REQUEST"
// export const SET_ADMINS = "ADMINS/SET"

// export const SET_CURRENT_ADMIN = "ADMINS/SET_CURRENT"
// export const POST_ADMIN = "ADMIN/POST"
// export const CREATE_ADMIN = "ADMINS/CREATE"
// export const EDIT_ADMIN = "ADMINS/EDIT"
// export const DELETE_ADMIN = "ADMINS/DELETE"


// export const REQUEST_POSTS = "POSTS/REQUEST"
// export const SET_POSTS = "POSTS/SET"

// export const SET_POST = "POSTS/SET_CURRENT"
// export const POST_POST = "POSTS/POST"
// export const EDIT_POST = "POSTS/EDIT"
// export const CREATE_POST = "POSTS/CREATE"
// export const DELETE_POST = "POSTS/DELETE"



// export const REQUEST_REPORTS = "--REPORTS/REQUEST"
// export const SET_REPORTS = "REPORTS/SET"

// export const SET_REPORT = "REPORTS/SET_CURRENT"
// export const POST_REPORT = "REPORTS/POST"
// export const EDIT_REPORT = "REPORTS/EDIT"
// export const CREATE_REPORT = "REPORTS/CREATE"
// export const DELETE_REPORT = "REPORTS/DELETE" 